### ISSUE TITLE
Try LXC

### ISSUE THREAD

**Issue by jpic** [mpasternak/vagrant-boxes#1]
Hey mate, have you tried LXC ? What do you think about it ? I like that it's pure and blazing fast, replaced vagrant for me - well sometimes i use vagrant with the lxc backend which works too.

**Comment by mpasternak** [comment]
I'm on Mac OS X, does it work here? Seems like I need another layer of VM to run LXC on. Except being more lightweight (as in CPU, RAM and disk space), I see LXC on Mac as being more complicated, as it introduces one more level of interaction.

**Comment by jpic** [comment]
True, so you should migrate on linux before you have the chance to use LXC heheheh

However, instead of having to spawn - and reserve memory for - 1 VM per machine, you could spawn only 1 VM and run all your machines inside it, using LXC for isolation. So, maybe it's worth a try anyway, you know, one day where you run out of memory ;)

Good job on the boxes BTW, they look pretty cool B)

**Comment by mpasternak** [comment]
btrfs snapshots look very interesting, I’ll definitely have a look into it, 

as for my boxes, I’m especially proud of utilizing vagrant-cashier and the selenium box - installing Firefox profile with a home page about:blank speeds up testing =)

**Comment by jpic** [comment]
Yeah, can't live without vagrant-cachier ! Did you try hitchtest ?

In projects where you can't use it, there's django-sbo-selenium, has
significantly improved my quality of life as a testonaut too ^^

**Comment by mpasternak** [comment]
For testing, I switched to pytest, as pytest-splinter and pytest-django are very good utils and you can just change the command line to test on different web driver.

**Comment by jpic** [comment]
Nice patches it has for selenium

https://github.com/pytest-dev/pytest-splinter/blob/master/pytest_splinter/webdriver_patches.py

I wonder if it's as good as sbo-selenium's though:

https://github.com/safarijv/sbo-selenium/blob/master/sbo_selenium/testcase.py

If it works well on travis without you having to do implement waits
yourself then it is as good for sure !
